# --------------------------------------------------------------------
# ‚ö†Ô∏è  THIS FILE IS MANAGED BY DEVOPS AUTOMATION
#
# üëâ What this means:
# - Changes may be overwritten by the central DevOps workflow.
#
# üëâ How to merge updates:
# - When you receive a DevOps workflow update PR, simply MERGE it to the
#   target branch (for most repos, this is `main`).
# - Do NOT cherry-pick or manually copy changes ‚Äî always merge the PR.
# - If you hit a merge conflict in `.github/*`, contact DevOps.
# --------------------------------------------------------------------
#
name: Pull Request Release Pipeline

on:        
  pull_request:
    types: [opened,reopened,labeled]
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
#!======================================= BETA =======================================!#
  helm-main-workflow:
    uses: updawg69/ci-reusable-workflows/.github/workflows/main-helm-beta-workflow.yml@main
    secrets: inherit
